// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: profiles.proto
// </auto-generated>

// Vendored namespaces adjusted: global::ProtoBuf. changed to global::Datadog.Trace.Vendors.ProtoBuf.

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Datadog.Tracer.OpenTelemetry.Proto.Profiles.V1
{

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class ProfilesData : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"resource_profiles")]
        public global::System.Collections.Generic.List<ResourceProfiles> ResourceProfiles { get; } = new global::System.Collections.Generic.List<ResourceProfiles>();

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class ResourceProfiles : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"resource")]
        public global::Datadog.Tracer.OpenTelemetry.Proto.Resource.V1.Resource Resource { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"scope_profiles")]
        public global::System.Collections.Generic.List<ScopeProfiles> ScopeProfiles { get; } = new global::System.Collections.Generic.List<ScopeProfiles>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"schema_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SchemaUrl { get; set; } = "";

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class ScopeProfiles : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"scope")]
        public global::Datadog.Tracer.OpenTelemetry.Proto.Common.V1.InstrumentationScope Scope { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"profiles")]
        public global::System.Collections.Generic.List<Profile> Profiles { get; } = new global::System.Collections.Generic.List<Profile>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"schema_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SchemaUrl { get; set; } = "";

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Profile : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"profile_id")]
        public byte[] ProfileId { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"start_time_unix_nano", DataFormat = global::Datadog.Trace.Vendors.ProtoBuf.DataFormat.FixedSize)]
        public ulong StartTimeUnixNano { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"end_time_unix_nano", DataFormat = global::Datadog.Trace.Vendors.ProtoBuf.DataFormat.FixedSize)]
        public ulong EndTimeUnixNano { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(4, Name = @"attributes")]
        public global::System.Collections.Generic.List<global::Datadog.Tracer.OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::Datadog.Tracer.OpenTelemetry.Proto.Common.V1.KeyValue>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(5, Name = @"dropped_attributes_count")]
        public uint DroppedAttributesCount { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(6, Name = @"original_payload")]
        public byte[] OriginalPayload { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(7, Name = @"stacktraces")]
        public global::System.Collections.Generic.List<Stacktrace> Stacktraces { get; } = new global::System.Collections.Generic.List<Stacktrace>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(8, Name = @"mappings")]
        public global::System.Collections.Generic.List<Mapping> Mappings { get; } = new global::System.Collections.Generic.List<Mapping>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(9, Name = @"locations")]
        public global::System.Collections.Generic.List<Location> Locations { get; } = new global::System.Collections.Generic.List<Location>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(10, Name = @"functions")]
        public global::System.Collections.Generic.List<Function> Functions { get; } = new global::System.Collections.Generic.List<Function>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(11, Name = @"links")]
        public global::System.Collections.Generic.List<Link> Links { get; } = new global::System.Collections.Generic.List<Link>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(12, Name = @"attribute_sets")]
        public global::System.Collections.Generic.List<AttributeSet> AttributeSets { get; } = new global::System.Collections.Generic.List<AttributeSet>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(13, Name = @"string_table")]
        public global::System.Collections.Generic.List<string> StringTables { get; } = new global::System.Collections.Generic.List<string>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(14, Name = @"profile_types")]
        public global::System.Collections.Generic.List<ProfileType> ProfileTypes { get; } = new global::System.Collections.Generic.List<ProfileType>();

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Link : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"trace_id")]
        public byte[] TraceId { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"span_id")]
        public byte[] SpanId { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class AttributeSet : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"attributes")]
        public global::System.Collections.Generic.List<global::Datadog.Tracer.OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::Datadog.Tracer.OpenTelemetry.Proto.Common.V1.KeyValue>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"dropped_attributes_count")]
        public uint DroppedAttributesCount { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Stacktrace : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"location_indices", IsPacked = true)]
        public uint[] LocationIndices { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class ProfileType : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"aggregation_temporality")]
        public AggregationTemporality AggregationTemporality { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"sample_rate")]
        public ulong SampleRate { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"type_index")]
        public uint TypeIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(4, Name = @"unit_index")]
        public uint UnitIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(10, Name = @"stacktrace_indices", IsPacked = true)]
        public uint[] StacktraceIndices { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(11, Name = @"link_indices", IsPacked = true)]
        public uint[] LinkIndices { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(12, Name = @"attribute_set_indices", IsPacked = true)]
        public uint[] AttributeSetIndices { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(13, Name = @"values", IsPacked = true)]
        public long[] Values { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(14, Name = @"timestamps", IsPacked = true)]
        public ulong[] Timestamps { get; set; }

    }
    
    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Mapping : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"memory_start")]
        public ulong MemoryStart { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"memory_limit")]
        public ulong MemoryLimit { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"file_offset")]
        public ulong FileOffset { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(4, Name = @"filename_index")]
        public uint FilenameIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(5, Name = @"build_id_index")]
        public uint BuildIdIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(6, Name = @"symbolic_info")]
        public SymbolFidelity SymbolicInfo { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(7, Name = @"attribute_set_indices", IsPacked = true)]
        public uint[] AttributeSetIndices { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Location : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"mapping_index")]
        public uint MappingIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"address")]
        public ulong Address { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"line")]
        public global::System.Collections.Generic.List<Line> Lines { get; } = new global::System.Collections.Generic.List<Line>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(5, Name = @"attribute_set_indices", IsPacked = true)]
        public uint[] AttributeSetIndices { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Line : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"function_index")]
        public uint FunctionIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2)]
        public uint line { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Function : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"name_index")]
        public uint NameIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"system_name_index")]
        public uint SystemNameIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"filename_index")]
        public uint FilenameIndex { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(4, Name = @"start_line")]
        public uint StartLine { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public enum AggregationTemporality
    {
        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoEnum(Name = @"AGGREGATION_TEMPORALITY_UNSPECIFIED")]
        AggregationTemporalityUnspecified = 0,
        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoEnum(Name = @"AGGREGATION_TEMPORALITY_DELTA")]
        AggregationTemporalityDelta = 1,
        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoEnum(Name = @"AGGREGATION_TEMPORALITY_CUMULATIVE")]
        AggregationTemporalityCumulative = 2,
    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public enum SymbolFidelity
    {
        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoEnum(Name = @"SYMBOL_FIDELITY_UNSPECIFIED")]
        SymbolFidelityUnspecified = 0,
        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoEnum(Name = @"SYMBOL_FIDELITY_FULL")]
        SymbolFidelityFull = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
