version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"

  # Maintain dependencies for Dockerfiles used in build pipeline
  - package-ecosystem: "docker"
    directory: "/tracer/build/_build/docker"
    schedule:
      interval: "weekly"
      day: "friday"

  # Below are the upstream settings that are disabed to reduce conflicts
  
  # Mocked projects for dependency notifications
  - package-ecosystem: "nuget"
    directory: "/tracer/dependabot"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:dependabot"
    ignore:
      - dependency-name: "MessagePack" # Locked at a version that supports our net452 build target
      - dependency-name: "*" # Ignore patches for all integrations
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 0 # disable version updates
  # Src libraries
  - package-ecosystem: "nuget"
    directory: "/tracer/src/Datadog.Trace"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:tracer"
    ignore:
      ### Start Datadog.Trace.csproj ignored dependencies
      # DiagnosticSource is kept at the lowest supported version for widest compatibility
      - dependency-name: "System.Diagnostics.DiagnosticSource"

      # AspNetCore reference libraries are kept at the lowest supported version for compatibility on netstandard2.0
      - dependency-name: "Microsoft.AspNetCore.Hosting.Abstractions"
      - dependency-name: "Microsoft.AspNetCore.Mvc.Abstractions"
      - dependency-name: "Microsoft.AspNetCore.Routing"

      # DuckTyping libraries are kept at the lowest supported version for compatibility on netstandard2.0
      - dependency-name: "System.Reflection.Emit"
      - dependency-name: "System.Reflection.Emit.Lightweight"
      ### End Datadog.Trace.csproj ignored dependencies

      # Lock Microsoft.Build.Framework for widest compatibility when instrumenting builds
      - dependency-name: "Microsoft.Build.Framework"
    open-pull-requests-limit: 0 # disable version updates

  - package-ecosystem: "nuget"
    directory: "/tracer/src/Datadog.Trace.OpenTracing"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:opentracing"
    ignore:
      ### Start Datadog.Trace.csproj ignored dependencies
      # DiagnosticSource is kept at the lowest supported version for widest compatibility
      - dependency-name: "System.Diagnostics.DiagnosticSource"

      # AspNetCore reference libraries are kept at the lowest supported version for compatibility on netstandard2.0
      - dependency-name: "Microsoft.AspNetCore.Hosting.Abstractions"
      - dependency-name: "Microsoft.AspNetCore.Mvc.Abstractions"
      - dependency-name: "Microsoft.AspNetCore.Routing"

      # DuckTyping libraries are kept at the lowest supported version for compatibility on netstandard2.0
      - dependency-name: "System.Reflection.Emit"
      - dependency-name: "System.Reflection.Emit.Lightweight"
      ### End Datadog.Trace.csproj ignored dependencies
    open-pull-requests-limit: 0 # disable version updates

  - package-ecosystem: "nuget"
    directory: "/tracer/src/Datadog.Trace.BenchmarkDotNet"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "area:benchmarks"
    ignore:
      ### Start Datadog.Trace.csproj ignored dependencies
      # DiagnosticSource is kept at the lowest supported version for widest compatibility
      - dependency-name: "System.Diagnostics.DiagnosticSource"

      # AspNetCore reference libraries are kept at the lowest supported version for compatibility on netstandard2.0
      - dependency-name: "Microsoft.AspNetCore.Hosting.Abstractions"
      - dependency-name: "Microsoft.AspNetCore.Mvc.Abstractions"
      - dependency-name: "Microsoft.AspNetCore.Routing"

      # DuckTyping libraries are kept at the lowest supported version for compatibility on netstandard2.0
      - dependency-name: "System.Reflection.Emit"
      - dependency-name: "System.Reflection.Emit.Lightweight"
      ### End Datadog.Trace.csproj ignored dependencies
    open-pull-requests-limit: 0 # disable version updates
