version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - datadog-agent
    environment:
      SIGNALFX_ENV: "apm-docker-samples"
      SIGNALFX_AGENT_HOST: "datadog-agent"
      SIGNALFX_TRACE_DEBUG: "true"
      ASPNETCORE_ENVIRONMENT: Production

  datadog-agent:
    image: "gcr.io/datadoghq/agent:7"
    environment:
      SIGNALFX_API_KEY: ${SIGNALFX_API_KEY}
      SIGNALFX_APM_ENABLED: "true"
      SIGNALFX_APM_NON_LOCAL_TRAFFIC: "true"
