extensions:
  health_check:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  opencensus:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  zipkin:

processors:
  batch:

exporters:
  logging:
    logLevel: debug

  zipkin:
    endpoint: https://ingest.us0.signalfx.com/v2/trace
    headers:
      # Splunk Observability Cloud accepts Basic auth where user=auth and password=access-token
      Authorization: Basic ${SPLUNK_AUTH_TOKEN}
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1

service:
  pipelines:
    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logging, jaeger, zipkin]
    metrics:
      receivers: [otlp, opencensus]
      processors: [batch]
      exporters: [prometheus]
      #exporters: [logging]

  extensions: [health_check, pprof, zpages]
