extensions:
  health_check:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  opencensus:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  zipkin:

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace"
  splunk_hec:
    token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v1/log"
  jaeger:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1

service:
  pipelines:
    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logging, jaeger, sapm]
    metrics:
      receivers: [otlp, opencensus]
      processors: [batch]
      exporters: [prometheus]
      #exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, splunk_hec]

  extensions: [health_check, pprof, zpages]
