// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: signal_fuse_protocol_buffers.proto
// </auto-generated>

// Vendored namespaces adjusted: global::ProtoBuf. changed to global::Datadog.Trace.Vendors.ProtoBuf.

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Datadog.Tracer.SignalFx.Metrics.Protobuf
{

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Datum : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string strValue
        {
            get => __pbn__strValue ?? "";
            set => __pbn__strValue = value;
        }
        public bool ShouldSerializestrValue() => __pbn__strValue != null;
        public void ResetstrValue() => __pbn__strValue = null;
        private string __pbn__strValue;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2)]
        public double doubleValue
        {
            get => __pbn__doubleValue.GetValueOrDefault();
            set => __pbn__doubleValue = value;
        }
        public bool ShouldSerializedoubleValue() => __pbn__doubleValue != null;
        public void ResetdoubleValue() => __pbn__doubleValue = null;
        private double? __pbn__doubleValue;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3)]
        public long intValue
        {
            get => __pbn__intValue.GetValueOrDefault();
            set => __pbn__intValue = value;
        }
        public bool ShouldSerializeintValue() => __pbn__intValue != null;
        public void ResetintValue() => __pbn__intValue = null;
        private long? __pbn__intValue;

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class Dimension : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string key
        {
            get => __pbn__key ?? "";
            set => __pbn__key = value;
        }
        public bool ShouldSerializekey() => __pbn__key != null;
        public void Resetkey() => __pbn__key = null;
        private string __pbn__key;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string value
        {
            get => __pbn__value ?? "";
            set => __pbn__value = value;
        }
        public bool ShouldSerializevalue() => __pbn__value != null;
        public void Resetvalue() => __pbn__value = null;
        private string __pbn__value;

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class DataPoint : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string source
        {
            get => __pbn__source ?? "";
            set => __pbn__source = value;
        }
        public bool ShouldSerializesource() => __pbn__source != null;
        public void Resetsource() => __pbn__source = null;
        private string __pbn__source;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string metric
        {
            get => __pbn__metric ?? "";
            set => __pbn__metric = value;
        }
        public bool ShouldSerializemetric() => __pbn__metric != null;
        public void Resetmetric() => __pbn__metric = null;
        private string __pbn__metric;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3)]
        public long timestamp
        {
            get => __pbn__timestamp.GetValueOrDefault();
            set => __pbn__timestamp = value;
        }
        public bool ShouldSerializetimestamp() => __pbn__timestamp != null;
        public void Resettimestamp() => __pbn__timestamp = null;
        private long? __pbn__timestamp;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(4)]
        public Datum value { get; set; }

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(5)]
        public MetricType metricType
        {
            get => __pbn__metricType.GetValueOrDefault();
            set => __pbn__metricType = value;
        }
        public bool ShouldSerializemetricType() => __pbn__metricType != null;
        public void ResetmetricType() => __pbn__metricType = null;
        private MetricType? __pbn__metricType;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<Dimension> dimensions { get; } = new global::System.Collections.Generic.List<Dimension>();

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class DataPointUploadMessage : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<DataPoint> datapoints { get; } = new global::System.Collections.Generic.List<DataPoint>();

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class PointValue : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3)]
        public long timestamp
        {
            get => __pbn__timestamp.GetValueOrDefault();
            set => __pbn__timestamp = value;
        }
        public bool ShouldSerializetimestamp() => __pbn__timestamp != null;
        public void Resettimestamp() => __pbn__timestamp = null;
        private long? __pbn__timestamp;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(4)]
        public Datum value { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public enum MetricType
    {
        GAUGE = 0,
        COUNTER = 1,
        ENUM = 2,
        CUMULATIVE_COUNTER = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
