//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeneratePackageVersions tool. To safely
//     modify this file, edit PackageVersionsGeneratorDefinitions.json and
//     re-run the GeneratePackageVersions project in Visual Studio. See the
//     launchSettings.json for the project if you would like to run the tool
//     with the correct arguments outside of Visual Studio.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Datadog.Trace.ClrProfiler.IntegrationTests
{
    [SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements must be separated by blank line", Justification = "This is an auto-generated file.")]
    public class PackageVersionsLatestMinors
    {
        public static IEnumerable<object[]> MongoDB =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "2.0.2" },
                new object[] { "2.1.1" },
                new object[] { "2.2.4" },
                new object[] { "2.3.0" },
                new object[] { "2.4.4" },
                new object[] { "2.5.1" },
                new object[] { "2.6.1" },
                new object[] { "2.7.3" },
                new object[] { "2.8.1" },
                new object[] { "2.9.3" },
                new object[] { "2.10.4" },
                new object[] { "2.11.6" },
                new object[] { "2.12.4" },
#endif
            };

        public static IEnumerable<object[]> ElasticSearch7 =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "7.0.1" },
                new object[] { "7.1.0" },
                new object[] { "7.2.1" },
                new object[] { "7.3.1" },
                new object[] { "7.4.2" },
                new object[] { "7.5.1" },
                new object[] { "7.6.2" },
                new object[] { "7.7.1" },
                new object[] { "7.8.2" },
                new object[] { "7.9.0" },
                new object[] { "7.10.1" },
                new object[] { "7.11.1" },
                new object[] { "7.12.1" },
                new object[] { "7.13.1" },
#endif
            };

        public static IEnumerable<object[]> ElasticSearch6 =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "6.0.2" },
                new object[] { "6.1.0" },
                new object[] { "6.2.0" },
                new object[] { "6.3.1" },
                new object[] { "6.4.2" },
                new object[] { "6.5.1" },
                new object[] { "6.6.0" },
                new object[] { "6.7.0" },
                new object[] { "6.8.8" },
#endif
            };

        public static IEnumerable<object[]> ElasticSearch5 =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "5.3.1" },
                new object[] { "5.4.0" },
                new object[] { "5.5.0" },
                new object[] { "5.6.6" },
#endif
            };

        public static IEnumerable<object[]> Npgsql =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "4.0.12" },
                new object[] { "4.1.3.1" },
#endif
            };

        public static IEnumerable<object[]> SqlClient =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "4.1.0" },
                new object[] { "4.3.1" },
                new object[] { "4.4.3" },
                new object[] { "4.5.3" },
                new object[] { "4.6.1" },
                new object[] { "4.7.0" },
                new object[] { "4.8.2" },
#endif
            };

        public static IEnumerable<object[]> StackExchangeRedis =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "1.0.488" },
                new object[] { "1.1.608" },
                new object[] { "1.2.6" },
                new object[] { "2.0.601" },
                new object[] { "2.1.58" },
                new object[] { "2.2.50" },
#endif
            };

        public static IEnumerable<object[]> ServiceStackRedis =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "4.0.62" },
                new object[] { "4.5.14" },
                new object[] { "5.0.2" },
                new object[] { "5.1.0" },
                new object[] { "5.2.0" },
                new object[] { "5.4.0" },
                new object[] { "5.5.0" },
                new object[] { "5.6.0" },
                new object[] { "5.7.0" },
                new object[] { "5.8.0" },
                new object[] { "5.9.2" },
                new object[] { "5.10.4" },
                new object[] { "5.11.0" },
#endif
            };

        public static IEnumerable<object[]> OpenTracing =>

            new List<object[]>
            {
#if DEFAULT_SAMPLES
                new object[] { string.Empty },
#else
                new object[] { "0.11.0" },
                new object[] { "0.12.1" },
#endif
            };

    }
}
