// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: profiles_service.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace OpenTelemetry.TestHelpers.Proto.Collector.Profiles.V1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ExportProfilesServiceRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"resource_profiles")]
        public global::System.Collections.Generic.List<global::OpenTelemetry.TestHelpers.Proto.Profiles.V1.ResourceProfiles> ResourceProfiles { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.TestHelpers.Proto.Profiles.V1.ResourceProfiles>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExportProfilesServiceResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"partial_success")]
        public ExportProfilesPartialSuccess PartialSuccess { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExportProfilesPartialSuccess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rejected_profiles")]
        public long RejectedProfiles { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorMessage { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
