// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: common.proto
// </auto-generated>

// Vendored namespaces adjusted: global::ProtoBuf. changed to global::Datadog.Trace.Vendors.ProtoBuf.

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Datadog.Tracer.OpenTelemetry.Proto.Common.V1
{

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class AnyValue : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"string_value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StringValue
        {
            get => __pbn__value.Is(1) ? ((string)__pbn__value.Object) : "";
            set => __pbn__value = new global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object(1, value);
        }
        public bool ShouldSerializeStringValue() => __pbn__value.Is(1);
        public void ResetStringValue() => global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 1);

        private global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object __pbn__value;

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"bool_value")]
        public bool BoolValue
        {
            get => __pbn__value.Is(2) ? __pbn__value.Boolean : default;
            set => __pbn__value = new global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeBoolValue() => __pbn__value.Is(2);
        public void ResetBoolValue() => global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 2);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"int_value")]
        public long IntValue
        {
            get => __pbn__value.Is(3) ? __pbn__value.Int64 : default;
            set => __pbn__value = new global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object(3, value);
        }
        public bool ShouldSerializeIntValue() => __pbn__value.Is(3);
        public void ResetIntValue() => global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 3);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(4, Name = @"double_value")]
        public double DoubleValue
        {
            get => __pbn__value.Is(4) ? __pbn__value.Double : default;
            set => __pbn__value = new global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object(4, value);
        }
        public bool ShouldSerializeDoubleValue() => __pbn__value.Is(4);
        public void ResetDoubleValue() => global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 4);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(5, Name = @"array_value")]
        public ArrayValue ArrayValue
        {
            get => __pbn__value.Is(5) ? ((ArrayValue)__pbn__value.Object) : default;
            set => __pbn__value = new global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object(5, value);
        }
        public bool ShouldSerializeArrayValue() => __pbn__value.Is(5);
        public void ResetArrayValue() => global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 5);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(6, Name = @"kvlist_value")]
        public KeyValueList KvlistValue
        {
            get => __pbn__value.Is(6) ? ((KeyValueList)__pbn__value.Object) : default;
            set => __pbn__value = new global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object(6, value);
        }
        public bool ShouldSerializeKvlistValue() => __pbn__value.Is(6);
        public void ResetKvlistValue() => global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 6);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(7, Name = @"bytes_value")]
        public byte[] BytesValue
        {
            get => __pbn__value.Is(7) ? ((byte[])__pbn__value.Object) : default;
            set => __pbn__value = new global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object(7, value);
        }
        public bool ShouldSerializeBytesValue() => __pbn__value.Is(7);
        public void ResetBytesValue() => global::Datadog.Trace.Vendors.ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 7);

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class ArrayValue : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"values")]
        public global::System.Collections.Generic.List<AnyValue> Values { get; } = new global::System.Collections.Generic.List<AnyValue>();

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class KeyValueList : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"values")]
        public global::System.Collections.Generic.List<KeyValue> Values { get; } = new global::System.Collections.Generic.List<KeyValue>();

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class KeyValue : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"value")]
        public AnyValue Value { get; set; }

    }

    [global::Datadog.Trace.Vendors.ProtoBuf.ProtoContract()]
    public partial class InstrumentationScope : global::Datadog.Trace.Vendors.ProtoBuf.IExtensible
    {
        private global::Datadog.Trace.Vendors.ProtoBuf.IExtension __pbn__extensionData;
        global::Datadog.Trace.Vendors.ProtoBuf.IExtension global::Datadog.Trace.Vendors.ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::Datadog.Trace.Vendors.ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(2, Name = @"version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Version { get; set; } = "";

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(3, Name = @"attributes")]
        public global::System.Collections.Generic.List<KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<KeyValue>();

        [global::Datadog.Trace.Vendors.ProtoBuf.ProtoMember(4, Name = @"dropped_attributes_count")]
        public uint DroppedAttributesCount { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
