---
- hosts: externals
  become: true
  tasks:
    - name: install iptables
      apt:
        name:
          - iptables
    - name: lock down the docker port so only the testbox can talk to it
      ansible.builtin.iptables:
        chain: INPUT
        action: insert
        protocol: tcp
        in_interface: '!lo'
        destination_port: 2375
        source: "!{{testbox_host}}"
        jump: DROP
    - name: install docker on ubuntu
      import_tasks: install-docker-playbook.yml
    - name: let docker listen on external port
      ansible.builtin.lineinfile:
        path: /lib/systemd/system/docker.service
        search_string: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock'
        line: 'ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375 --containerd=/run/containerd/containerd.sock'
    - name: tell systemd about the config change on disk
      ansible.builtin.command:
        cmd: systemctl daemon-reload
    - name: restart docker daemon after config change
      ansible.builtin.service:
        name: docker
        state: restarted
    - name: lock down dependencies ports just for testbox
      ansible.builtin.iptables:
        chain: DOCKER-USER
        action: insert
        protocol: tcp
        in_interface: '!lo'
        destination_ports:
          # logs receiver
          - 4318
          # trace receiver
          - 9411
          # metric receiver
          - 9943
          # sqlserver
          - 1433
        source: "!{{testbox_host}}"
        jump: DROP
    - name: copy collector yaml
      ansible.builtin.copy:
        src: ../../src/Docker/otel-config.yaml
        dest: /home/splunk/
        owner: splunk
        group: users
        mode: '0644'