//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace SignalFx.Tracing.Vendors.StatsdClient
{
    internal interface IStatsdUDP
    {
        void Send(string command);
    }
}