//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace SignalFx.Tracing.Vendors.StatsdClient
{
    internal interface IStopwatch
    {
        void Start();
        void Stop();
        int ElapsedMilliseconds();
    }
}